name: CI

on:
  pull_request:
    branches: [ "main", "release/**"]

jobs:
  build:
    name: Test
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: |
          set -o pipefail
          xcodebuild test -scheme UtilsTests -destination 'platform=iOS Simulator,OS=17.0,name=iPhone 11' -testPlan TestPlan | xcpretty

  swiftlint:
    name: Swiftlint
    needs: build
    runs-on: self-hosted
    steps:
      - name: Linting
        run: swiftlint --config .swiftlint.yml

  clear:
    name: Clear
    needs: [build, swiftlint]
    if: always()
    runs-on: self-hosted
    steps:
      - name: Clean up
        run: cd ../.. && rm -rf SwiftCV
